### ISSUE TITLE
Modify name as stored in history?

### ISSUE THREAD

**Issue by slestak** [yoichiro/url_shortener_extension#10]
I am using your tool to create short links to my clients redmine instances.  That means in the history, it is just displaying Redmine repeatedly.  The url behind it is different and acts as desired.

Could we get the ability to modify the description of the shortened link?  That way I could label them Redmine_Client1, Redmine_Client2, etc?

**Comment by yoichiro** [comment]
Your idea will be supported at the next version. In the next version, when you shift-click the long URL in the history list, an input field will be shown to modify the title string.

**Comment by yoichiro** [comment]
The new version 1.36.0 has just been released. This version allows you to change the page's title. Try it!
