### ISSUE TITLE
Option to watch existing URLs

### ISSUE THREAD

**Issue by gavaletz** [yoichiro/url_shortener_extension#6]
I really like the watch feature that you have implemented.  If I send a link to someone for review, then I have a better idea of when they actually get around to it.  That said, I was messing around with the tool and there was a "stop watching" link.  It did stop watching the links.  What is not there is any way to undo what it did.  Having a option that cannot be undone and with no warning that it cannot be undone is problematic.  My humble suggestion:

Use the check boxes that you have on the left to implement the watching feature.  Instead of having them "display with high priority" have them watched with the implication that watching an item will display it with high priority.  Then you can get rid of the "stop watching" link since checked items will be watched.

**Comment by yoichiro** [comment]
Thank you for your suggestion. You mentioned that the undo operation could not be found after clicking "stop watching", but you can restart the watching by clicking the shortened URL which you want to watch the click count. That is, if you click the shortened URL in the history list, the web page was not opened, instead, the shortened URL will be copied to your clip board and the watching of the click count will be started.

Of course, I think that your idea looks good to me. At least, I intend to add the function to start the watching when an user checks the "display with high priority" checkbox.

How does that sound?

**Comment by yoichiro** [comment]
I have just released the new version 1.30.0. This version includes the new option to set whether the watching is started or not at checking each high priority checkbox.

https://github.com/yoichiro/url_shortener_extension/commit/e4aa58883f61a489be8c9dd08a34442b5e80de98

Feel free to let me know any issues if you will have them. Thanks!
