### ISSUE TITLE
Duplicate handling

### ISSUE THREAD

**Issue by slestak** [yoichiro/url_shortener_extension#9]
If I accidentally shorten a url that is already in my watch list, I do not see a way to remove it.
I see that you cannot remove goo.gl urls anyway.  Maybe we can get access to the Hide method at goo.gl

Would it be possible to check to see if the url is already present in your watchlist and bring it to the users attn before adding it a second time?  This seems possible since you already have a access to our shortened links.

Oh, and thank you very much for your extension, its very helpful.

Edited: rephrased request after I see that deletion is not possible

**Comment by yoichiro** [comment]
Thank you for reporting its issue. I intend to confirm this behavior and fix it soon.

**Comment by yoichiro** [comment]
I have just released the new version 1.35.0 supported your idea. An URL already registered into your history is no longer added. Of course, you can turn on the previous behavior by using the option page.

https://github.com/yoichiro/url_shortener_extension/commit/2b12d22a4429f48e31c746e2c0c41750a7dee0fa

Thank you for reporting your good idea! :)

**Comment by slestak** [comment]
Thank you Yoichiro
